---
managedNamespaces: []
createClusterScopedResources: true
webhook:
  enabled: true
resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 512Mi
#podAnnotations:
#  sidecar.istio.io/inject: "true"
#  traffic.sidecar.istio.io/includeInboundPorts: "*"
#  traffic.sidecar.istio.io/excludeInboundPorts: "9443"
